apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
type: Opaque
data:
  VITE_SUPABASE_URL: aHR0cHM6Ly90cHplbndrbXd3b2dkb2hqendzcy5zdXBhYmFzZS5jbw==
  VITE_SUPABASE_ANON_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5Sd2VtVnVkMnR0ZDNkdloyUnZhR3A2ZDNOeklpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTkRFMU9EY3hNRE1zSW1WNGNDSTZNakExTnpFMk16RXdNMzAuUnVCQ004RXRXYzlVMlNzVkF2ZkVIeUdSTmthYzN3VEdpTkgydVRJUTR0aw==
